### ISSUE TITLE
Two questions about this library and realtimes simultaneos connections

### ISSUE THREAD

**Issue by efitrillo** [mobizt/Firebase-ESP-Client#103]
Greetings, first I'd like to say thanks for this library. 
After reading the docs I have two matters unclear. 

1) If I listen to changed on two nodes for example with multipath, would this count on firebase as 2 simultaneous connections? Or only 1
2) If I update some values of a node for example with setInt and be done with it, would this count as a connection? As Im not using a stream? Then I would be able to do as many continuous updates no matter connections only data transfer (As example blaze plan is 200k max connections)

Best regards

**Comment by mobizt** [comment]
If your device stay connected, all server event-stream data that pushed to client will not be missed.

You can use different Firebase Data objects for multiple stream sessions, but careful about low memory.

If you have question, use [Discussions](https://github.com/mobizt/Firebase-ESP-Client/discussions) instead.

The request from all functions that store and read data will count to the transaction count.

The question about Firebase APIs, policies and usages, please contact google or post your question on stackoverflow.

This is the library repository.
