### ISSUE TITLE
Firestore GetDocument example not working but others like create, patch they work fine. haha

### ISSUE THREAD

**Issue by aseitasi15** [mobizt/Firebase-ESP-Client#112]
**Describe the bug**
The Firebase-ESP-Client is testing with a couple of my ESP32. Firebase's Firestore DB is ready and also user's email and pw are set too.

Among the examples you provided, CreateDocuments, PathDocument works well without any problems. 

But in GetDocument, 

if (Firebase.Firestore.getDocument(&fbdo, FIREBASE_PROJECT_ID, "", documentPath.c_str(), mask.c_str()))
          Serial.printf("ok\n%s\n\n", fbdo.payload().c_str());
      else
          Serial.println(fbdo.errorReason());

If I run the getDocument method, I got this error.

Get a document... Guru Meditation Error: Core 1 panic'ed (LoadProhibited). Exception was unhandled 

Your getDocument method is 
bool FB_Firestore::getDocument(FirebaseData *fbdo, const char *projectId, const char *databaseId, const char *documentPath, const char *mask, const char *transaction, const char *readTime)

The last two parameters don't need? 
All works fine but is the only getDocument is not working on my end? it's weird. Any clue for this?

**To Reproduce**
Firestore/GetDocument/GetDocument.ino

**IDE and its version:**
 - Arduino IDE 2.0, & Arduino IDE 1.8.13

**Test devices**
 - ESP32 Dev Module
 - ESP32 Wemos Lolin32

**Comment by mobizt** [comment]
You should follow the issue template by providing the minimum clean code.
