### ISSUE TITLE
BUG - Firestore - Getdocument v2.4.4

### ISSUE THREAD

**Issue by quentin-gilli** [mobizt/Firebase-ESP-Client#122]
Hi, 

**Describe the bug**
I can't get a document from Firestore for a few hours on my esp32
I was on a few weeks old version of your library 
but after updated to the last version (v2.4.4) it is still the same.

**To Reproduce**
1. Launched the GetDocument example from Firestore folder with your credential. 
2. The file will be created on your Firestore database 
3. But your ESP32 will be stuck after serial print "Get a document..."
4. Nothing happen in several minutes....

**IDE and its version:**
 - Arduino
 - Version v2.4.4

**ESP32 Arduino Core SDK version**
 - Espressif systems version 1.0.6 --> I'm not sure it's the right answer.

**Comment by mobizt** [comment]
Thanks for report this bug.

The bug was fixed, please update the library to [v2.4.5](https://github.com/mobizt/Firebase-ESP-Client/releases/tag/v2.4.5).

**Comment by quentin-gilli** [comment]
Thank you !
