### ISSUE TITLE
Regarding Fetching data once and setting the GPIOs

### ISSUE THREAD

**Issue by PranavJ99** [mobizt/Firebase-ESP-Client#128]
Hello @mobizt , I am trying to get the data from my firebase database for once so that i can set the GPIOs according to the database before my esp32 was resetted. But I cant find any relevent source, please help me regarding this.
Thank You.

p.s.:Basically it will work as eeprom without eeprom

**Comment by mobizt** [comment]
You need to try the examples how to use the library properly. There are many examples, this is the basic usage.
https://github.com/mobizt/Firebase-ESP-Client/blob/main/examples/RTDB/Basic/Basic.ino

This is the library repository for the issue. You can apply to use what you want to do which I can't help on this.
