### ISSUE TITLE
BUG - Firestore create document without name ?

### ISSUE THREAD

**Issue by quentin-gilli** [mobizt/Firebase-ESP-Client#198]
Hello @mobizt 

Thank you for your amazing library. 

I just would like to report a change of behavior in the management of Firebase Documents (maybe intended, maybe a bug):

- Indeed, on my production board (not updated for month), in the Firestore.createDocument function, I can specify a documentPath like this "Foldername/" and let Firestore assign it an ID (example: 6Pnkf9lu2qSEpXuvMkD2) (still work today).

- In the new versions of your lib, filling a documentPath without the name of the document returns an error : 
  Resource id "Foldername/\" is invalid because it contains "/\".

(Of course I can get around the problem by entering a document name (not tried yet))

**IDE and its version:**
 - Arduino
 - Version 1.8.13

**Lib version:**
- at least 2.6.5 to 2.7.0

**ESP32 Arduino Core SDK version**
 - Version 2.0.1-RC1  and, updated during my test to 2.0.1

**Comment by mobizt** [comment]
This is not a bug and you should use it properly at first.

Refer to the relative uri with the trailing slash has no meaning and it equal to uri itself.
