### ISSUE TITLE
Create Document - Firestore failed

### ISSUE THREAD

**Issue by PrateekGoyal18** [mobizt/Firebase-ESP-Client#20]
Hey Mobizt, 

Just love your repos man!

I am trying to get ahold of the create document example, but getting this error:
```
Create a document...
FAILED
REASON:
```
Can you please check this.

P.S. - I am using Nodemcu v0.9

**Comment by mobizt** [comment]
Invalid authentication info.

For Firestore examples, you need to add the API key to the example when you log in with Email/Password.
See the RTDB example for authentication reference.

**Comment by mobizt** [comment]
Add this two lines
https://github.com/mobizt/Firebase-ESP-Client/blob/main/examples/RTDB/Basic/Basic.ino#L26
https://github.com/mobizt/Firebase-ESP-Client/blob/main/examples/RTDB/Basic/Basic.ino#L61

**Comment by PrateekGoyal18** [comment]
I am now getting the error: 
```
FAILED
REASON: Missing or insufficient permissions.
```

My security rules are open as you gave in documentation:
service cloud.firestore {
  match /databases/{database}/documents {
    match /todos/{document=**} {
      allow read, write: if true;
    }
  }
}

**Comment by mobizt** [comment]
Please read [this](https://github.com/mobizt/Firebase-ESP-Client#authentication).

**Comment by PrateekGoyal18** [comment]
So I should get the Service accounts key JSON file?

**Comment by mobizt** [comment]
You should enable the Email sign-in provider if you Email/Password sign-in method.

After enable that, you can create user from the console or from library.

Please read more about Firebase Authentication from Google Firebase document.

**Comment by PrateekGoyal18** [comment]
Done all that. After that only getting the error.

**Comment by mobizt** [comment]
Read Firebase doc
