### ISSUE TITLE
Firebase RTDB 

### ISSUE THREAD

**Issue by PerumalD** [mobizt/Firebase-ESP-Client#229]
I tried to download the data from rtdb ...It is received successfully. But not write in SD. But successfully write 1kb file but not write large files
Firebase ESp client version :2.7.5
![esp](https://user-images.githubusercontent.com/33823888/148911975-007ed930-7235-4a61-80b3-cd51b2e7b68c.png)

**Comment by mobizt** [comment]
You should follow the issue template when you open the issue.

I can't help without information, code and debug message.

Your code to post here should keep minimal and clear which everyone can test it without third party libraries.

**Comment by PerumalD** [comment]
Okay. I will posted.

**Comment by PerumalD** [comment]
void loop()
{

  if (Firebase.ready() && !taskCompleted)
  {
    taskCompleted = true;

    //File name must be in 8.3 DOS format (max. 8 bytes file name and 3 bytes file extension)
    Serial.printf("Set file... %s\n", Firebase.RTDB.setFile(&fbdo, mem_storage_type_sd, "test/file/data3", "/file2.txt") ? "ok" : fbdo.errorReason().c_str());

    Serial.printf("Get file... %s\n", Firebase.RTDB.getFile(&fbdo, mem_storage_type_sd, "test/file/data3", "/file3.txt") ? "ok" : fbdo.errorReason().c_str());

    if (fbdo.httpCode() == FIREBASE_ERROR_HTTP_CODE_OK)
    {

#if defined(ESP32)
      Firebase.sdBegin(13, 14, 2, 15); //SS, SCK,MISO, MOSI
#elif defined(ESP8266)
      Firebase.sdBegin(15);  //SS
#endif

      //Readout the downloaded file
      file = DEFAULT_SD_FS.open("/file3.txt", FILE_READ);
      int i = 0;

      while (file.available())
      {
        if (i > 0 && i % 16 == 0)
          Serial.println();

        uint8_t v = file.read();

        if (v < 16) 
          Serial.print("0");

        Serial.print(v, HEX);
        Serial.print(" ");
        i++;
      }

      Serial.println();
      file.close();
    }
  }
}

**Comment by PerumalD** [comment]
`void loop()
{

  if (Firebase.ready() && !taskCompleted)
  {
    taskCompleted = true;

    //File name must be in 8.3 DOS format (max. 8 bytes file name and 3 bytes file extension)
    Serial.printf("Set file... %s\n", Firebase.RTDB.setFile(&fbdo, mem_storage_type_sd, "test/file/data3", "/file2.txt") ? "ok" : fbdo.errorReason().c_str());

    Serial.printf("Get file... %s\n", Firebase.RTDB.getFile(&fbdo, mem_storage_type_sd, "test/file/data3", "/file3.txt") ? "ok" : fbdo.errorReason().c_str());

    if (fbdo.httpCode() == FIREBASE_ERROR_HTTP_CODE_OK)
    {

#if defined(ESP32)
      Firebase.sdBegin(13, 14, 2, 15); //SS, SCK,MISO, MOSI
#elif defined(ESP8266)
      Firebase.sdBegin(15);  //SS
#endif

      //Readout the downloaded file
      file = DEFAULT_SD_FS.open("/file3.txt", FILE_READ);
      int i = 0;

      while (file.available())
      {
        if (i > 0 && i % 16 == 0)
          Serial.println();

        uint8_t v = file.read();

        if (v < 16) 
          Serial.print("0");

        Serial.print(v, HEX);
        Serial.print(" ");
        i++;
      }

      Serial.println();
      file.close();
    }
  }
}`

**Comment by PerumalD** [comment]
`
[issues.txt](https://github.com/mobizt/Firebase-ESP-Client/files/7845155/issues.txt)
`

**Comment by PerumalD** [comment]
```void loop()
{

  if (Firebase.ready() && !taskCompleted)
  {
    taskCompleted = true;

    //File name must be in 8.3 DOS format (max. 8 bytes file name and 3 bytes file extension)
    Serial.printf("Set file... %s\n", Firebase.RTDB.setFile(&fbdo, mem_storage_type_sd, "test/file/data3", "/file2.txt") ? "ok" : fbdo.errorReason().c_str());

    Serial.printf("Get file... %s\n", Firebase.RTDB.getFile(&fbdo, mem_storage_type_sd, "test/file/data3", "/file3.txt") ? "ok" : fbdo.errorReason().c_str());

    if (fbdo.httpCode() == FIREBASE_ERROR_HTTP_CODE_OK)
    {

#if defined(ESP32)
      Firebase.sdBegin(13, 14, 2, 15); //SS, SCK,MISO, MOSI
#elif defined(ESP8266)
      Firebase.sdBegin(15);  //SS
#endif

      //Readout the downloaded file
      file = DEFAULT_SD_FS.open("/file3.txt", FILE_READ);
      int i = 0;

      while (file.available())
      {
        if (i > 0 && i % 16 == 0)
          Serial.println();

        uint8_t v = file.read();

        if (v < 16) 
          Serial.print("0");

        Serial.print(v, HEX);
        Serial.print(" ");
        i++;
      }

      Serial.println();
      file.close();
    }
  }
}```

**Comment by mobizt** [comment]
> You should follow the issue template when you open the issue.
> 
> I can't help without information, code and debug message.
> 
> Your code to post here should keep minimal and clear which everyone can test it without third party libraries.

**Comment by PerumalD** [comment]
Okay. Downloading the Large files using rtdb. shows this error .
"response payload read timed out due to network issue or too large data size"

**Comment by mobizt** [comment]
If you read the issue template, you will see the required information hint.

I don't know which device, sdk version you used.

Read the comments in the example, you will see the guide when you want to work with large file in esp8266.

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP-Client/blob/6142af83ddc3f8e71ce9a5a2cc80b4445dfe6474/examples/RTDB/File/SD/SD.ino#L88-L91

**Comment by PerumalD** [comment]
Thanks.. But i tried 1kb file successfully write. but 21 kb file not write

**Comment by mobizt** [comment]
**fbdo.setBSSLBufferSize(16384, 1024);**

This will consume your mem about 17k+ during operation.

**Comment by mobizt** [comment]
You should use the [storage](https://github.com/mobizt/Firebase-ESP-Client/tree/main/examples/Storage) for large file upload/download because in RTDB we need to encrypt as base64 string which the size will go bigger.

**Comment by PerumalD** [comment]
Tried in Firebase storage also shows . It seems to be Download File I/0 Error

**Comment by mobizt** [comment]
The problem is your SD card or adapter. Check the looseness of cables wiring. The library works with many megabytes files upload and download without problem.

**Comment by PerumalD** [comment]
Thanks. Kindly advise them . How to give your file name path in Storage Bucket. It is a getDownloadurl path????

**Comment by mobizt** [comment]
Yes, check the comment in the examples when the download url is empty.

**Comment by PerumalD** [comment]
How much time take for 1mb file to upload / Download??

**Comment by mobizt** [comment]
The [new version](https://github.com/mobizt/Firebase-ESP-Client/releases/tag/v2.8.0) is available with bugs fixed and features added included SdFat support for 5 times faster file read/write, the progress callback for file upload/download.

Please try.

**Comment by PerumalD** [comment]
Sure. I will try and feedback to you

**Comment by PerumalD** [comment]
Download Failed. File I/o Error

**Comment by mobizt** [comment]
You should read the comment in all new examples.

You must choose SD from [here](https://github.com/mobizt/Firebase-ESP-Client/blob/main/src/FirebaseFS.h) and change sd interfaces [here](https://github.com/mobizt/Firebase-ESP-Client/blob/main/src/addons/SDHelper.h).

Fire I/O error is because your SD card is not ready e.g. mounted failed or SPI configuration is not matched to your connection.

**Comment by PerumalD** [comment]
Mounting sd card success..

**Comment by mobizt** [comment]
SPI configuration is not matched to your connection.

**Comment by PerumalD** [comment]
old Version. 2.7.7 it works Perfectly

**Comment by mobizt** [comment]
Or the card is failed or cannot access during read/write.

The library always check the media access for every data access.

It's not related to the library version as you think.

**Comment by mobizt** [comment]
The old version is loosely check for data access and SD initialization cannot customized.

**Comment by mobizt** [comment]
If the amount of data that successfully write or read does not match the byte to write or read, the new library will report the File I/O error while the old version ignore this check and continue to read or write other position.

This means your card is not ready (temporary access failed or SPI connection disconnected) during the continuous read or write.

**Comment by PerumalD** [comment]
Thanks to guide.. I will check

**Comment by PerumalD** [comment]
Everything is correct configured!!.  Same issue found in ESP-12F Firebase image download

**Comment by mobizt** [comment]
I strongly sure that you have problem with the hardware as I have been tested SD thoroughly on ESP32 and ESP8266 devices.

**Comment by mobizt** [comment]
You should run the SD card test on your device and check the checksum of data that read and write.

**Comment by PerumalD** [comment]
sd card Format in Fat16/Fat32  or else fat

**Comment by mobizt** [comment]
FAT or FAT32 is ok except for exFAT and NTFS.

You should try another card.

**Comment by PerumalD** [comment]
External ram is needed for nodemcu 12f?

**Comment by mobizt** [comment]
No, you should read it, they're options which now available in IDE and sdk v3.0.x.
https://github.com/mobizt/Firebase-ESP-Client#memory-options-for-esp8266

**Comment by PerumalD** [comment]
yeah .. Just now also try perfectly work in 2.7.7 .... File size should be 2mb approx. But Updating the version 2.8,.0 not downloading in firebase storage

**Comment by PerumalD** [comment]
`void loop()
{
    if (Firebase.ready() && !taskCompleted)
    {
        taskCompleted = true;
    
        Serial.println("\nUpload file...\n");

        //MIME type should be valid to avoid the download problem.
        //The file systems for flash and SD/SDMMC can be changed in FirebaseFS.h.
        if (!Firebase.Storage.upload(&fbdo, STORAGE_BUCKET_ID /* Firebase Storage bucket id */, "/testbmp1.bmp" /* path to local file */, mem_storage_type_sd /* memory storage type, mem_storage_type_flash and mem_storage_type_sd */, "testbmp1.bmp" /* path of remote file stored in the bucket */, "images/bmp" /* mime type */, fcsUploadCallback /* callback function */))
            Serial.println(fbdo.errorReason());
    }
}`

**Comment by mobizt** [comment]
Everything was ok and checked in v2.8.0.

**Comment by mobizt** [comment]
Do you enable external heap in IDE config even you don't have external SRAM in esp8266?

**Comment by PerumalD** [comment]
No.. ...

**Comment by mobizt** [comment]
I don't know File I/O error report immediately when trying to open read file or during upload process.

You should check the new examples which the progress callback was added.
Test it and post the debug message here.
