### ISSUE TITLE
RTDB - Multipath stream not working

### ISSUE THREAD

**Issue by kumbhat10** [mobizt/Firebase-ESP-Client#265]
**Just ask something**
If you have questions, use [Discussions](https://github.com/mobizt/Firebase-ESP-Client/discussions) instead. 

**Describe the bug**
In the below code, Multipath streaming doesn't start as it used to before. I was using multipath stream before and it was working fine but suddenly stopped working now. I don't remember which previous version of Firebase-ESP-Client I was using

**To Reproduce**
#include <WiFi.h>
#include <Firebase_ESP_Client.h>
#include <addons/TokenHelper.h>
#include <addons/RTDBHelper.h>

#define WIFI_SSID "xxxxxxxx"
#define WIFI_PASSWORD "xxxxxxxxx"
#define API_KEY "xxxxxxxxxsl4hxxxxxxxxxI"
#define DATABASE_URL "https://xxx-xxx-default-rtdb.europe-west1.firebasedatabase.app"
#define USER_EMAIL "xxxxx@gmail.com"
#define USER_PASSWORD "xxxxx"

FirebaseData fbdo;
FirebaseData stream;
FirebaseAuth auth;
FirebaseConfig config;
unsigned long sendDataPrevMillis = 0;

String parentPath = "/test/stream/data";
String childPath[2] = {"/node1", "/node2"};

int count = 0;
volatile bool dataChanged = false;

void streamCallback(MultiPathStream stream)
{
  size_t numChild = sizeof(childPath) / sizeof(childPath[0]);
  for (size_t i = 0; i < numChild; i++)
  {
    if (stream.get(childPath[i]))
    {
      Serial.printf("path: %s, event: %s, type: %s, value: %s%s", stream.dataPath.c_str(), stream.eventType.c_str(), stream.type.c_str(), stream.value.c_str(), i < numChild - 1 ? "\n" : "");
    }
  }
  Serial.println();
  Serial.printf("Received stream payload size: %d (Max. %d)\n\n", stream.payloadLength(), stream.maxPayloadLength());
  dataChanged = true;
}

void streamTimeoutCallback(bool timeout)
{
  if (timeout)
    Serial.println("stream timed out, resuming...\n");
  if (!stream.httpConnected())
    Serial.printf("error code: %d, reason: %s\n\n", stream.httpCode(), stream.errorReason().c_str());
}

void setup()
{
  Serial.begin(115200);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to Wi-Fi");
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(300);
  }
  Serial.println();  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());  Serial.println();
  Serial.printf("Firebase Client v%s\n\n", FIREBASE_CLIENT_VERSION);

  config.api_key = API_KEY;
  auth.user.email = USER_EMAIL;  auth.user.password = USER_PASSWORD;
  config.database_url = DATABASE_URL;
  config.token_status_callback = tokenStatusCallback; //see addons/TokenHelper.h
  Firebase.begin(&config, &auth);  Firebase.reconnectWiFi(true);

  Serial.println("Start firebase streaming");
  if (!Firebase.RTDB.beginMultiPathStream(&stream, parentPath))
    Serial.printf("sream begin error, %s\n\n", stream.errorReason().c_str());
  Firebase.RTDB.setMultiPathStreamCallback(&stream, streamCallback, streamTimeoutCallback);
}

void loop()
{
  if (Firebase.ready() && (millis() - sendDataPrevMillis > 15000 || sendDataPrevMillis == 0))
  {
    sendDataPrevMillis = millis();
    Serial.print("Set json...\n");
    FirebaseJson json;
    for (size_t i = 0; i < 2; i++)
    {
      json.set("node1/data", "v1");
      json.set("node1/num", count);
      json.set("node2/data", "v2");
      json.set("node2/num", count * 3);
      Firebase.RTDB.setJSONAsync(&fbdo, parentPath, &json);
      count++;
    }
    Serial.println("JSON set ok\n");
  }
  if (dataChanged)
  {
    dataChanged = false;
    Serial.println("Data changed");
  }
}

**Expected behavior**
Get updates with path and value whenever it changes in RTDB - it was working fine before but not anymoreW

**IDE and its version:**
 - Arduino
 - Version [1.8.19]

**ESP32 Arduino Core SDK version**
 - Version [1.0.6]

**Additional context**
I have tried using callback function example from this library and it works fine. Just that multipath callback example doesn't work anymore.
Below is the output from my serial monitor

11:34:11.054 -> [D][esp32-hal-psram.c:47] psramInit(): PSRAM enabled
11:34:11.201 -> [D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
11:34:11.247 -> [D][WiFiGeneric.cpp:374] _eventCallback(): Event: 2 - STA_START
11:34:11.247 -> Connecting to Wi-Fi........[D][WiFiGeneric.cpp:374] _eventCallback(): Event: 4 - STA_CONNECTED
11:34:13.463 -> [D][WiFiGeneric.cpp:374] _eventCallback(): Event: 7 - STA_GOT_IP
11:34:13.463 -> [D][WiFiGeneric.cpp:419] _eventCallback(): STA IP: 192.168.218.246, MASK: 255.255.255.0, GW: 192.168.218.155
11:34:13.604 -> 
11:34:13.604 -> Connected with IP: 192.168.218.246
11:34:13.604 -> 
11:34:13.604 -> Firebase Client v3.1.2
11:34:13.604 -> 
11:34:13.604 -> Token info: type = id token, status = on request
11:34:13.651 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:13.651 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:13.651 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:13.651 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:13.651 -> [V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 247276
11:34:13.651 -> [V][ssl_client.cpp:65] start_ssl_client(): Starting socket
11:34:13.698 -> [V][ssl_client.cpp:104] start_ssl_client(): Seeding the random number generator
11:34:13.698 -> [V][ssl_client.cpp:113] start_ssl_client(): Setting up the SSL/TLS structure...
11:34:13.744 -> [I][ssl_client.cpp:127] start_ssl_client(): WARNING: Skipping SSL Verification. INSECURE!
11:34:13.744 -> [V][ssl_client.cpp:197] start_ssl_client(): Setting hostname for TLS session...
11:34:13.744 -> [V][ssl_client.cpp:212] start_ssl_client(): Performing the SSL/TLS handshake...
11:34:15.469 -> [V][ssl_client.cpp:233] start_ssl_client(): Verifying peer X.509 certificate...
11:34:15.469 -> [V][ssl_client.cpp:242] start_ssl_client(): Certificate verified.
11:34:15.469 -> [V][ssl_client.cpp:257] start_ssl_client(): Free internal heap after TLS 203328
11:34:15.469 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 285 bytes...
11:34:15.785 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.785 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.785 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.785 -> Token info: type = id token, status = ready
11:34:15.785 -> Start firebase streaming
11:34:15.785 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.785 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.785 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.823 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.823 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.823 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:15.823 -> [V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 249176
11:34:15.823 -> [V][ssl_client.cpp:65] start_ssl_client(): Starting socket
11:34:15.870 -> [V][ssl_client.cpp:104] start_ssl_client(): Seeding the random number generator
11:34:15.870 -> [V][ssl_client.cpp:113] start_ssl_client(): Setting up the SSL/TLS structure...
11:34:15.870 -> [I][ssl_client.cpp:127] start_ssl_client(): WARNING: Skipping SSL Verification. INSECURE!
11:34:15.870 -> [V][ssl_client.cpp:197] start_ssl_client(): Setting hostname for TLS session...
11:34:15.870 -> [V][ssl_client.cpp:212] start_ssl_client(): Performing the SSL/TLS handshake...
11:34:16.836 -> [V][ssl_client.cpp:233] start_ssl_client(): Verifying peer X.509 certificate...
11:34:16.836 -> [V][ssl_client.cpp:242] start_ssl_client(): Certificate verified.
11:34:16.836 -> [V][ssl_client.cpp:257] start_ssl_client(): Free internal heap after TLS 205484
11:34:16.836 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 32 bytes...
11:34:16.836 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 902 bytes...
11:34:16.883 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 191 bytes...
11:34:16.883 -> Set json...
11:34:16.883 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:16.883 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:16.883 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:16.883 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:16.883 -> [V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
11:34:16.883 -> [V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 195376
11:34:16.883 -> [V][ssl_client.cpp:65] start_ssl_client(): Starting socket
11:34:16.930 -> [V][ssl_client.cpp:104] start_ssl_client(): Seeding the random number generator
11:34:16.930 -> [V][ssl_client.cpp:113] start_ssl_client(): Setting up the SSL/TLS structure...
11:34:16.930 -> [I][ssl_client.cpp:127] start_ssl_client(): WARNING: Skipping SSL Verification. INSECURE!
11:34:16.930 -> [V][ssl_client.cpp:197] start_ssl_client(): Setting hostname for TLS session...
11:34:16.977 -> [V][ssl_client.cpp:212] start_ssl_client(): Performing the SSL/TLS handshake...
11:34:17.937 -> [V][ssl_client.cpp:233] start_ssl_client(): Verifying peer X.509 certificate...
11:34:17.937 -> [V][ssl_client.cpp:242] start_ssl_client(): Certificate verified.
11:34:17.937 -> [V][ssl_client.cpp:257] start_ssl_client(): Free internal heap after TLS 151692
11:34:17.937 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 32 bytes...
11:34:17.937 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 902 bytes...
11:34:17.937 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 256 bytes...
11:34:17.937 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 61 bytes...
11:34:17.985 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 32 bytes...
11:34:17.985 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 902 bytes...
11:34:17.985 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 256 bytes...
11:34:17.985 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 61 bytes...
11:34:17.985 -> JSON set ok
11:34:17.985 -> 
11:34:31.877 -> Set json...
11:34:31.877 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 32 bytes...
11:34:31.877 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 902 bytes...
11:34:31.877 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 256 bytes...
11:34:31.877 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 61 bytes...
11:34:31.877 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 32 bytes...
11:34:31.920 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 902 bytes...
11:34:31.920 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 256 bytes...
11:34:31.920 -> [V][ssl_client.cpp:295] send_ssl_data(): Writing HTTP request with 61 bytes...
11:34:31.920 -> JSON set ok

**Comment by kumbhat10** [comment]
I have tried using https://github.com/mobizt/Firebase-ESP32 library also with provided multipath and  callback example.  Multipath example doesn't work but callback example works like a charm

**Comment by mobizt** [comment]
Thanks for reporting this bug.

The library update [v3.1.3](https://github.com/mobizt/Firebase-ESP-Client/releases/tag/v3.1.3) is available with this bug fixed.

**Comment by kumbhat10** [comment]
I have tested with v3.1.3 and it is working again. Thanks for fixing this issue. However I had to manually download the .zip code and then use it. Any idea how long will it take for Arduino library manager to show update available. As I am having CI/CD pipeline, and want to build and update firmware of all my ESP32's automatically
