### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by EmbedXYZ** [mobizt/Firebase-ESP-Client#3]
Hello, i'm using firebase stream on ESP8288
it works good but i have the following question :
when i leave it for a long time it become idle and refuse to get any stream data until i restart it. 
i noticed the following defines in common.h
 #define KEEP_ALIVE_TIMEOUT 45000
#define STREAM_ERROR_NOTIFIED_INTERVAL 3000
#define STREAM_RECONNECT_INTERVAL 1000

the question is what if i need the connection alive forever without timeout?

**Comment by mobizt** [comment]
It's not possible in this kind of connection, the stream is the http connection which keep the connection alive as long as the server connected. If connection lost the http connection will be closed.

The library tries it best to reconnect the WiFi when  you calling  the function **Firebase.reconnectWiFi (true)** once in the setup and the stream will be resumed .

I explain this so many times in the Firebase-ESP32 and Firebasr-ESP8266 repositories.

If stream timed out and never connected anymore, you should check the WiFi router for internet connectivity.

Do not change these predefined timeout and interval values in common.h.

**Comment by EmbedXYZ** [comment]
Thanks
