### ISSUE TITLE
HELP - REASON: INVALID_PASSWORD

### ISSUE THREAD

**Issue by giselybelloadur** [mobizt/Firebase-ESP-Client#32]
I'm trying to use the Stream example from the Firebase_ESP_Client library and the following error is happening:
  -> Set string ...
  -> FAILED
  -> REASON: INVALID_PASSWORD

Where do I need to validate the email and password to use in the code?

**Comment by mobizt** [comment]
The user that you created in the project.

The users tab in Authentication, see the picture below
https://github.com/mobizt/Firebase-ESP-Client/blob/main/media/images/Enable_Email_Password_Provider.png

**Comment by mobizt** [comment]
You can use the [Discussions](https://github.com/mobizt/Firebase-ESP-Client/discussions) for the question and help.

**Comment by giselybelloadur** [comment]
Hello, thank you so much for replying.

I already did that, and put my email and email password in the project, but
the password is invalid. Why?

Em qui., 11 de mar. de 2021 às 09:49, mobizt ***@***.***>
escreveu:

**Comment by mobizt** [comment]
No thing else more than your trying to log in with user in other project instead of your provided project in the code.

Make sure you log in with user of that project and provide the valid host name (FIREBASE_AUTH) , in case you create  many projects. 

If your project host name (Fire

**Comment by mobizt** [comment]
Please do not reply from email, please go to Github in case I edit the message.
