### ISSUE TITLE
Firebase ESP32 "token is not ready"

### ISSUE THREAD

**Issue by Danesh2712** [mobizt/Firebase-ESP-Client#339]
Hello, I cant seem to connect to my database and i get the message 'token is not ready' whenever im trying to send a value to database 

 if(gesture_dec.startsWith("RIGHT")){
    page = 4;
    gesture_dec = "";
    gesture = "";
    value1 = "Bad";
  if (Firebase.RTDB.setString(&fbdo, "user/User_Review" ,value1)){
     Serial.println("PASSED");
      Serial.println("PATH: " + fbdo.dataPath());
      Serial.println("TYPE: " + fbdo.dataType());
    }
    else {
      Serial.println("FAILED");
      Serial.println("REASON: " + fbdo.errorReason());
    }

**Comment by mobizt** [comment]
Follow the examples first.
