### ISSUE TITLE
Can use set() and pathExisted()

### ISSUE THREAD

**Issue by 4dok** [mobizt/Firebase-ESP-Client#37]
**Describe the bug**
after V2.0.7 I can't verify a pathExisted() and can't publish a array on a RTDB.

**To Reproduce**
Firebase.RTDB.pathExisted(&fbdo2, Path.c_str())
this function is retuning "1" with a path that do not exists.

Firebase.RTDB.set(&fbdo2, Path.c_str(), relayConfig);
this function returns "Invalid data; couldn't parse JSON object, array, or value."

**IDE and its version:**
 - Arduino IDE 1.8.13

**ESP8266 Arduino Core SDK version**
 - ESP8266 (WEMOS D1 mini)
 SDK: 2.2.2-dev(38a443e)
 core:2_7_4

**Code**
[code.zip](https://github.com/mobizt/Firebase-ESP-Client/files/6223548/code.zip)

**Comment by mobizt** [comment]
The bugs fixed in version 2.0.12 and please update.
