### ISSUE TITLE
ENHANCEMENT - AUTO CONNECTION

### ISSUE THREAD

**Issue by giorgio80** [mobizt/Firebase-ESP-Client#375]
It could happen that when device is starting no internet connection is available ( ex. power loss, both device and Router Restart). 

I noticed that if launch the client when connection is available it does work correctly and automatically reconnect in case of disconnection.

if I launch the client and WiFi is not available at the moment I call the Firebase.begin() the reconnection does not work. 

It would be possible the client connect automatically also in this case by just creating the object or I have to manage the situation manually ? 

Best Regard

**Comment by mobizt** [comment]
You can call `Firebase.begin(`) when your device offline (no WiFi or internet) because it is only credentials storing,

When you call `Firebase.ready(`) it will try to resume WiFi with the Core SDK function `WiFi.reconnect()` as long as you set `Firebase.reconnectWiFi(true)`.
