### ISSUE TITLE
esp_eth_driver_install(215) error

### ISSUE THREAD

**Issue by KJPOUNDY132** [mobizt/Firebase-ESP-Client#382]
hi, how can i solve this problem "esp_eth_driver_install(215)"

**Comment by mobizt** [comment]
This is not library related issue but ESP32 Arduino Core SDK issue and I can't help.

For the ethernet driver issue, you should test with [these examples](https://github.com/espressif/arduino-esp32/tree/master/libraries/Ethernet/examples) and if you get the error, please open the issue [here](https://github.com/espressif/arduino-esp32/issues).
