### ISSUE TITLE
auth_revoked in multipath stream after some time

### ISSUE THREAD

**Issue by maxakash** [mobizt/Firebase-ESP-Client#389]
Hi
I am using multipath stream but after around 30-40 minutes, I am not able to listen to any changes.
Here is the code output

```
path: /diningchandelier/OnOff, event: auth_revoked, type: , value: {"on":true}
```
Please suggest what am I doing wrong.

Thanks

**Comment by mobizt** [comment]
Please don't open the issue. You should use discussion.

**Comment by maxakash** [comment]
> Please don't open the issue. You should use discussion.

Sorry my bad.
