### ISSUE TITLE
using SD_MMC

### ISSUE THREAD

**Issue by ehababdalnaby** [mobizt/Firebase-ESP-Client#399]
How can I use SD_MMC to upload files to firebase storage?
Board: ESP 32

**Comment by mobizt** [comment]
You should see look at the examples e.g., [this example](https://github.com/mobizt/Firebase-ESP-Client/blob/main/examples/Storage/FirebaseStorage/DownloadFile/DownloadFile.ino).

See the SD_MMC discussion https://github.com/mobizt/Firebase-ESP-Client/discussions/352
