### ISSUE TITLE
[Questions] Can ESP32 automatic get changed data from Firestore like RTDB?

### ISSUE THREAD

**Issue by jatu-studiobox** [mobizt/Firebase-ESP-Client#404]
Hi,
I used to use your library 'Firebase ESP32 Client', work with Firebase Realtime database. If data has changed, it can automatic get changed data from server to ESP32.
I am not sure, if I use this library 'Firebase-ESP-Client', work with Firestore database. Can ESP32 automatic get changed data from Firestore like RTDB?
Please advise me.

Thank you very much

**Comment by mobizt** [comment]
Not supported in REST API.

**Comment by jatu-studiobox** [comment]
Thank you very much :)
