### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by bensalcie** [mobizt/Firebase-ESP-Client#41]
Here is an error I get after running the basic rtdb , any guide on this please?
Thanks.
                In file included from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client- 
                main\src/common.h:45:0,

                 from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client-main\src/Utils.h:37,

                 from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client-main\src/signer/Signer.h:37,

                 from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client-main\src/Firebase_ESP_Client.h:37,

                 from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client- 
                main\examples\RTDB\Basic\Basic.ino:18:

                  C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client- 
                   main\src/wcs/esp8266/FB_HTTPClient.h:50:30: fatal error: CertStoreBearSSL.h: No such file or directory

                  #include <CertStoreBearSSL.h>

                              ^

**Comment by mobizt** [comment]
You should update ESSP8266  Arduino Core SDK to the latest version.

**Comment by bensalcie** [comment]
> Here is an error I get after running the basic rtdb , any guide on this please?
> Thanks.
> In file included from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client-
> main\src/common.h:45:0,
> 
> ```
>              from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client-main\src/Utils.h:37,
> 
>              from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client-main\src/signer/Signer.h:37,
> 
>              from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client-main\src/Firebase_ESP_Client.h:37,
> 
>              from C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client- 
>             main\examples\RTDB\Basic\Basic.ino:18:
> 
>               C:\Users\Dev. Ben Salcie\Documents\Arduino\libraries\Firebase-ESP-Client- 
>                main\src/wcs/esp8266/FB_HTTPClient.h:50:30: fatal error: CertStoreBearSSL.h: No such file or directory
> 
>               #include <CertStoreBearSSL.h>
> 
>                           ^
> ```



> You should update ESSP8266 Arduino Core SDK to the latest version.

Thanks a lot Bro for the fast response and the time. Next time you could consider stating this in the documentation. Thanks a lot

**Comment by mobizt** [comment]
The ESP8266 SDK you're using is almost 2-3 years released as it used axTLS as SSL engine instead of the later version that has bot axTLS and BearSSL.

**Comment by mobizt** [comment]
This library is the unified and upgrade version of FirebaseESP8266 and FirebaseESP32 libraries which relied on BearSSL and mbedTLS libraries which required for token signing.

The doc of FirebaseESP8266 library also state the supported ESP8266 SDK version. Everyone that migrates from that library is already known.
