### ISSUE TITLE
improving compilation time

### ISSUE THREAD

**Issue by wydmynd** [mobizt/Firebase-ESP-Client#466]
Hello, we have a CS academic course that [many projects use your library](https://github.com/orgs/ICST-Technion/repositories).

Most projects use RTDB or Firestore on ESP32 (soon starting RP2040) , many are having issues with the long compilation time. over 2 minutes on a modern laptop using Arduino IDE. 

1. what would you recommend to improve this? is there a way to un-include unnecessary parts of the library? 
2. What version of the ESP32 SDK for Arduino IDE would you recommend? Is there an advantage in moving to platformio?

thanks in advance

**Comment by mobizt** [comment]
It depends on many things from tool chains, your java, OS, firewall/antivirus and hardware.

In PlatformIO, it can compile faster than in ArduinoIDE.

You can exclude the filesystem library and other libraries in `FirebaseFS.h` that already wrote on Readme.
