### ISSUE TITLE
I can't initialise 

### ISSUE THREAD

**Issue by Mesihas** [mobizt/Firebase-ESP-Client#467]
**Describe the bug**
I can't initialise,  just loaded the example "Basic" tried to compile but doesn't

**To Reproduce**
Just installed Arduino IDE 2

Installed Library "[Firebase-ESP-Client](https://github.com/mobizt/Firebase-ESP-Client)"
version 4.3.1

This is the only library I have installed

**Expected behavior**
Compile

**Screenshots**
Get this error

```
In file included from /Users/alemac/Library/Arduino15/libraries/SD/src/utility/Sd2Card.h:26:0,
                 from /Users/alemac/Library/Arduino15/libraries/SD/src/utility/SdFat.h:29,
                 from /Users/alemac/Library/Arduino15/libraries/SD/src/SD.h:20,
                 from /Users/alemac/Documents/Arduino/libraries/Firebase_ESP32_Client/src/FirebaseFS.h:59,
                 from /Users/alemac/Documents/Arduino/libraries/Firebase_ESP32_Client/src/Firebase.h:34,
                 from /Users/alemac/Documents/Arduino/libraries/Firebase_ESP32_Client/src/FirebaseESP32.h:49,
                 from /private/var/folders/21/1sgjllhx4_98vhm8_5tnr06r0000gn/T/.arduinoIDE-unsaved2023020-443-mh18hw.89a7d/Basic/Basic.ino:16:
/Users/alemac/Library/Arduino15/libraries/SD/src/utility/Sd2PinMap.h:524:2: error: #error Architecture or board not supported.
 #error Architecture or board not supported.
  ^
Multiple libraries were found for "SD.h"
  Used: /Users/alemac/Library/Arduino15/libraries/SD
  Not used: /Users/alemac/Library/Arduino15/packages/esp32/hardware/esp32/1.0.6/libraries/SD
exit status 1

Compilation error: exit status 1
```

**IDE and its version:**
 - Arduino IDE v2

**Additional context**
I have a working version (old) on my laptop, the library compiles and all good. I just wanted to install on a new computer so I installed Arduino, boards, all connected and working but the moment i want to compile the basic example it cant.

**Comment by mobizt** [comment]
You should remove this Firebase esp32 only version library at `/Users/alemac/Documents/Arduino/libraries/Firebase_ESP32_Client`

And remove the SD library that is not compatible with ESP platforms at `/Users/alemac/Library/Arduino15/libraries/SD`

**Comment by Mesihas** [comment]
"You should remove this Firebase esp32 only version library at /Users/alemac/Documents/Arduino/libraries/Firebase_ESP32_Client"

This is the library installed by arduino IDE if I remove it I won't have "Firebase-ESP-Client" that I want to

"And remove the SD library that is not compatible with ESP platforms at /Users/alemac/Library/Arduino15/libraries/SD"
This library is not installed ( at least it is not present on Arduino library

**Comment by mobizt** [comment]
As you see the error that you already installed Firebase-ESP32 library here
` from /Users/alemac/Documents/Arduino/libraries/Firebase_ESP32_Client/src/FirebaseFS.h:59,`

And you post on this repo Firebase ESP Client library for ESP8266 and ESP32 which I assume that you want to install then I ask you to remove  Firebase-ESP32 library first.

You have intsalled 3rd party SD library here in your Arduino system which conflicts with ESP32 SD library here
`/Users/alemac/Library/Arduino15/libraries/SD`

Then I ask you to delete those two folders.

All information I know is from the compiler error that show the reason for me to verify what is wrong.

**Comment by mobizt** [comment]
There are many Firebase libraries that developed by me.

1. FirebaseESP8266 for ESP8266 and Raspberry Pi Pico that supports realtime database and cloud messaging.

2. FirebaseESP32 for ESP32 only that supports realtime database and cloud messaging.

3. Firebase ESP Client in this repository is for ESP32, ESP8266, Raspberry Pi Pico and many devices that supports realtime database, cloud Firestore, Firebase storage, Google Cloud Storage, Cloud Functions and Cloud Messaging.

If you want to install FirebaseESP32 library, you are posting in the wrong repository.  You only need to remove the SD library in Arduino libraries folder.

There are Firebase libraries available for SAMD21 devices that work with WiFiNINA and WiFi101 libraries which develop by me.

Please read the library description before install to make sure you install the right library.

**Comment by Mesihas** [comment]
Thanks, now I understand.  I have the project working on my laptop. The library installed is "Google's Firebase Realtime Database Arduino Library for ESP32 v3.15.5" according to README.md, is that number 2 on your comment?

Somehow the folder name for the installed library is"Firebase_ESP32_Client" which made me think is number 3

**Comment by mobizt** [comment]
Yes, number 2.
