### ISSUE TITLE
Firebase Real Time Database setStreamCallback method stops trigger callback after a while 

### ISSUE THREAD

**Issue by etanh** [mobizt/Firebase-ESP-Client#469]
A different amount of time after each successful firebase initialization with call to "setStreamCallback" the callback method and the timeoutCallback method stop execute at all.

After each restart it's works perfectly, but after a while it stops working without any notification and all error message seems to return OK status.

I added a different log method that write timestamp parameter to the RTDB every 30 seconds and it is continue to work hours after the listener is stops working, 

```
#include <Arduino.h>
#include <WiFi.h>
#include <Firebase_ESP_Client.h>
// #include <FirebaseESP32.h>
#include <stdlib.h>

#include <addons/TokenHelper.h>
#include <addons/RTDBHelper.h>

FirebaseData fbdGate;
FirebaseAuth auth;
FirebaseConfig config;

int commandValue = 0;
int commandValueLast = -1;

int64_t commandTime = 0;
int64_t commandTimeLast = -1;

long timerCommand = -1;
long timerKeepAlive = 0;

void streamCallback(FirebaseStream data)
{
  Serial.println("streamCallback");
  
  //change the commandValue and commandTime parameters
  ....
}

void streamTimeoutCallback(bool timeout)
{
  if (timeout)
    Serial.println("stream timed out, resuming...\n");

  if (!fbdGate.httpConnected())
    Serial.printf("error code: %d, reason: %s\n\n", fbdGate.httpCode(), fbdGate.errorReason().c_str());
}


void setup()
{
  Serial.begin(115200);

  config.database_url = "DB_URL";
  config.api_key = "API_KEY";

  auth.user.email = "EMAIL";
  auth.user.password = "PASS";

  config.token_status_callback = tokenStatusCallback;

  WiFi.mode(WIFI_STA);

  WiFi.begin("SSID", "PASS");
  Serial.print("Connecting to Wi-Fi");

  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(300);
  }

  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();

  Firebase.begin(&config, &auth);
  Firebase.reconnectWiFi(true);
  Firebase.setDoubleDigits(5);

  if (!Firebase.RTDB.beginStream(&fbdGate, "/somepath/command"))
  {
    Serial.printf("sream begin error, %s\n\n", fbdGate.errorReason().c_str());
  }

  Firebase.RTDB.setStreamCallback(&fbdGate, streamCallback, streamTimeoutCallback);
}


void loop()
{

  if (commandValue != commandValueLast || commandTime != commandTimeLast)
  {
    Serial.println("Command Changed");
    Serial.printf("Command Value: %d, Command Value Last: %d\n", commandValue, commandValueLast);
    Serial.printf("Command Time: %lld, Command Time Last: %lld\n", commandTime, commandTimeLast);

    commandTimeLast = commandTime;
    commandValueLast = commandValue;

    FirebaseData data;
    FirebaseJson fj;
    fj.add("command/value", commandValue);
    fj.add("command/time", commandTime);
    Firebase.RTDB.updateNode(&data, F("/somepath"), &fj);
  }

  // some code that runs every 30 sec
  {
    FirebaseData data;
    Firebase.RTDB.setTimestamp(&data, "log");
    Serial.println("Timer Keep Alive - Tick ");
    Serial.println(data.errorReason());
    setTimer(&timerKeepAlive);

    if (!fbdGate.httpConnected())
      Serial.printf("error code: %d, reason: %s\n\n", fbdGate.httpCode(), fbdGate.errorReason().c_str());
    else
      Serial.println("fbdGate Connected");
  }

  delay(10);
}
```

The output is:

> Connecting to Wi-Fi.......
> Connected with IP: xx.xx.xx.xx
> 
> Token info: type = id token (GITKit token), status = on request
> Token info: type = id token (GITKit token), status = ready
> streamCallback
> Command Changed
> Command Value: 0, Command Value Last: -1
> Command Time: xxxxxxxxxxx, Command Time Last: -1
> Timer Keep Alive - Tick 
> unknown error
> fbdGate Connected
> Timer Keep Alive - Tick 
> unknown error
> fbdGate Connected
> Timer Keep Alive - Tick 
> unknown error
> fbdGate Connected

And I can see that every 30 sec the log value is updated but after a while when I change the command value at the RTDB it's stops trigger the callback method  (the log is still working)

**IDE and its version:**
 - ESP32, PlatformIO
 - platform = espressif32
 - board = esp32-s2-saola-1
 - framework = arduino
 - build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
 - lib_deps = mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.3.4

**ESP32 Arduino Core SDK version**
 - v4.4-beta1-189-ga79dc75f0a

**Comment by mobizt** [comment]
You will see this such comment in all examples.
https://github.com/mobizt/Firebase-ESP-Client/blob/60b3d7a2ca416181e7d2a4ccc11682009e996ab8/examples/RTDB/Basic/Basic.ino#L167-L172

You should follow it to use library correctly.
