### ISSUE TITLE
Esp32 firestore without auth

### ISSUE THREAD

**Issue by KJPOUNDY132** [mobizt/Firebase-ESP-Client#475]
Hi i want to use firestore without email auth, is it possible?

**Comment by mobizt** [comment]
The authentication methods required to use Google Firebase services in this library are already stated in Readme doc and also in all examples.
https://github.com/mobizt/Firebase-ESP-Client/blob/b79a7412cc9b5c15893503a4304640221a14196c/examples/Firestore/CreateDocuments/CreateDocuments.ino#L13

**Comment by mobizt** [comment]
If you mean no auth or public access, please read [this](https://github.com/mobizt/Firebase-ESP-Client#firebase-cloud-firestore) for the security rules setting for public access.

And set the test mode for no auth in the config.

`config.signer.test_mode = true;`

**Comment by KJPOUNDY132** [comment]
U say there is no way to use without auth like Service account keys (like python firestore)

**Comment by mobizt** [comment]
Read what I reply again.

**Comment by KJPOUNDY132** [comment]
Sorry i dont see it:)
