### ISSUE TITLE
Compilation error: 'FirebaseStorage' does not name a type

### ISSUE THREAD

**Issue by Animesh452** [mobizt/Firebase-ESP-Client#481]
I am using AI Thinker ESP32 Cam board in Arduino IDE and getting the above compilation error. Please help resolve this.
Firebase ESP32 Client by Mobizt v4.3.7
![image](https://user-images.githubusercontent.com/68946005/219781734-e35c9422-2549-4f81-a4d3-f0bad322fc8e.png)

**Comment by mobizt** [comment]
Firebase ESP32 Client library supports RTDB and FCM only.

Firebase Arduino Client Library for ESP8266 and ESP32 library (this repo) supports RTDB, FCM, Firestore, Storage. Google Cloud Storage and Functions for Firebase.

Choose the correct library in Arduino Library Manager to install.

**Comment by mobizt** [comment]
This library must be removed.
https://github.com/mobizt/Firebase-ESP32
