### ISSUE TITLE
HELP what protocol is used for communication with firebase server: plain https, ws or grpc?

### ISSUE THREAD

**Issue by velcrine** [mobizt/Firebase-ESP-Client#50]
Just want to clarify what protocol does firebase official clients use vs what protocol we are using.

**Comment by mobizt** [comment]
http through REST APIs.

**Comment by mobizt** [comment]
You can use [Discussion](https://github.com/mobizt/Firebase-ESP-Client/discussions) to ask questions.

**Comment by velcrine** [comment]
thanks @mobizt
