### ISSUE TITLE
Firebase storage

### ISSUE THREAD

**Issue by Geethukulal** [mobizt/Firebase-ESP-Client#512]
Hy, can i use the nano rp2040 connect board for send the files to firebase storage which stored in sd card.

**Comment by mobizt** [comment]
You should use discussion for asking a question.

As I wrote in library documentation, the supported SDK is [Arduino Pico](https://github.com/earlephilhower/arduino-pico). 

With this SDK it was support SD filesystem.

[Arduino Core for mbed](https://github.com/arduino/ArduinoCore-mbed) was not support by this library.
