### ISSUE TITLE
printResult function definition and location

### ISSUE THREAD

**Issue by usrrsr** [mobizt/Firebase-ESP-Client#52]
I have gone through rtdb examples which uses function printResult(fbdo2) frequently but i dont see where it is located

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP-Client/blob/c84728f92f792c845e1adea205f6884f93f4d3f6/examples/RTDB/Basic/Basic.ino#L23

https://github.com/mobizt/Firebase-ESP-Client/blob/main/src/addons/RTDBHelper.h

**Comment by mobizt** [comment]
Please use [Discussions](https://github.com/mobizt/Firebase-ESP-Client/discussions) for the question.
