### ISSUE TITLE
After document creation, the timestamp value changes.

### ISSUE THREAD

**Issue by youdonut** [mobizt/Firebase-ESP-Client#520]
After document generation, the timestamp value in the Firestore database changes.

`content.set("fields/myTimestamp/timestampValue", time); // RFC3339 UTC "Zulu" format`

![untitled](https://github.com/mobizt/Firebase-ESP-Client/assets/85593647/9b66b9ca-5d6c-44ef-8917-ffef7dc8dfb2)

I'm in the UTC+8 time zone.

**Comment by mobizt** [comment]
That is because of your code instead.

**Comment by youdonut** [comment]
> That is because of your code instead.

Yes, sir, I have fixed this.
After reading this,
[https://medium.easyread.co/understanding-about-rfc-3339-for-datetime-formatting-in-software-engineering-940aa5d5f68a](url)
