### ISSUE TITLE
ENHANCEMENT

### ISSUE THREAD

**Issue by Riddheshbhamre** [mobizt/Firebase-ESP-Client#586]
**Just ask something**
If you have questions, use [Discussions](https://github.com/mobizt/Firebase-ESP-Client/discussions) instead. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I am using library <firebase esp client.h> and I have a code which simply sent int,float data to firebase but and I am using firebase.setfloat I am enclave error as no member found in the library this is urgent

**Comment by mobizt** [comment]
You should follow [this example](https://github.com/mobizt/Firebase-ESP-Client/blob/main/examples/RTDB/Basic/Basic.ino).
