### ISSUE TITLE
Firestore Get, Query, List examples returns incorect document name in payload 

### ISSUE THREAD

**Issue by ev-olution** [mobizt/Firebase-ESP-Client#620]
All Firestore examples which return payload has issues with document name. For example I get the following payload output on serial:

`Get a document... ok
{
  "name": "projects/stripe-webhook-d1xxxx/databases/(default)/documents/info/countries",
  "fields": {
    "Singapore": {
      "mapValue": {
        "fields": {
          "population": {
            "integerValue": "5703600"
          },
          "time_zone": {
            "integerValue": "8"
          }
        }
      }
    }
  },
  "createTime": "2024-01-04T00:40:24.270730Z",
  "updateTime": "2024-01-04T00:40:24.270730Z"
}`

Document name is returned as full document path (including server path), but not as actual name, which in this case is "countries". How I can make it return real document name, instead of path? Thanks

**Comment by mobizt** [comment]
It is upon Google Firestore APIs and features, we can't do anything.
