### ISSUE TITLE
token usage with Alexa skills or Google assistant

### ISSUE THREAD

**Issue by ateker01** [mobizt/Firebase-ESP-Client#623]
Greetings,

I apologize in advance that this is not in the scope of this very project but considering how helpful the followers of the library have been I was hoping someone will help me with this question.

I can read and write to the firebase using the tokens with email and password authentication. What I would like to achieve is to create Google Assistant and Alexa skill to read data from the firebase. However I can not figure out how to authenticate with email and password in other words the account linking part.
I have done extensive search with no luck so I wanted to reach out as I am hoping that someone also needed to setup a skill and they could direct me to a tutorial or a similar project page.

**Comment by mobizt** [comment]
Sorry, this is the library repository issue section, and it is not community forum.

You should ask your question in community forum instead.

**Comment by ateker01** [comment]
my bad! I will ask the question under the discussions
