### ISSUE TITLE
Token is generated but the set command causes ESP8266 to crash

### ISSUE THREAD

**Issue by ateker01** [mobizt/Firebase-ESP-Client#636]
I have a sample set command issued after token generation but the command not only fails but also crashes the ESP8266. 
I confirm that this is not related to firebase rules or anything on the firebase. 
Actually this has worked forever until I upgraded the WiFiManager by tzapu. I can modify the WiFiManager header but have no clue what is the root cause of the problem.
Any idea what is causing this problem?

Here is the serial output

17:07:42.263 -> *wm:StartAP with SSID:  CXXXXX84
17:07:43.295 -> *wm:AP IP address: 192.168.4.1
17:07:43.295 -> *wm:Starting Web Portal 
17:08:25.639 -> *wm:8 networks found
17:08:34.320 -> *wm:8 networks found
17:08:43.362 -> *wm:Connecting to NEW AP: XXXX-79
17:08:43.487 -> *wm:connectTimeout not set, ESP waitForConnectResult... 
17:08:46.714 -> *wm:Connect to new AP [SUCCESS] 
17:08:46.714 -> *wm:Got IP Address: 
17:08:46.714 -> *wm:192.168.1.68 
17:08:46.714 -> Should save config
17:08:47.719 -> *wm:config portal exiting 
17:08:47.719 -> Connected.
17:08:49.237 -> Token info: type = id token (GITKit token), status = on request
17:08:50.585 -> Token info: type = id token (GITKit token), status = ready
17:08:50.990 -> path is : /fazz/f0bd84
17:08:58.626 -> 
17:08:58.626 ->  ets Jan  8 2013,rst cause:4, boot mode:(3,6)
17:08:58.626 -> 
17:08:58.626 -> wdt reset

Here is the code.... 

// ADDED firebase credentials
// Define Firebase objects
FirebaseData firebaseData;
FirebaseAuth auth;
FirebaseConfig config;

  init_fb();
  delay(100);

  path="/fazz/"+uniqueID;
  Serial.println("path is : " + path);
  if(Firebase.RTDB.setBool(&firebaseData, path, true))
  {
     Serial.println("Set fazz success");
  }else{
    firebaseData.errorReason().c_str();
  }

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP-Client?tab=readme-ov-file#memory-options
