### ISSUE TITLE
sdfat can't be used as sd file system

### ISSUE THREAD

**Issue by JoergTiedemann** [mobizt/Firebase-ESP-Client#638]
Hi
I've tried to use SDFat in firebase libray but no way, I got compilation error message:

.pio/libdeps/esp32dev/Firebase Arduino Client Library for ESP8266 and ESP32/src/rtdb/FB_RTDB.cpp: In member function 'uint8_t FB_RTDB::readQueueFileSdFat(FirebaseData*, SdFile&, QueueItem&, uint8_t)': .pio/libdeps/esp32dev/Firebase Arduino Client Library for ESP8266 and ESP32/src/rtdb/FB_RTDB.cpp:1355:17: error: 'FBUtils::idle' is not a class member Core.ut.FBUtils::idle(); ^~~~~~~ .pio/libdeps/esp32dev/Firebase Arduino Client Library for ESP8266 and ESP32/src/rtdb/FB_RTDB.cpp:1362:29: error: 'FBUtils::idle' is not a class member Core.ut.FBUtils::idle(); ^~~~~~~ *** [.pio\build\esp32dev\lib83a\Firebase Arduino Client Library for ESP8266 and ESP32\rtdb\FB_RTDB.cpp.o] Error 1
I have added the folowing to CustomFirebaseFS.h

`#include <SdFat.h> //https://github.com/greiman/SdFat
#undef DEFAULT_SD_FS // remove SD defined macro
#undef CARD_TYPE_SD // remove SD defined macro

static SdFat sd_fat_fs; //should declare as static here
#define DEFAULT_SD_FS sd_fat_fs
#define CARD_TYPE_SD 1
#define SD_FS_FILE SdFile `

The question is: what I have to do to integrate SdFat to firebase library ?

I use actual sdk, actual firebase library and sdfat in newest version

**Comment by mobizt** [comment]
You can update the library to fix the issue.
