### ISSUE TITLE
Filesystem should be a user choice

### ISSUE THREAD

**Issue by cotestatnt** [mobizt/Firebase-ESP-Client#64]
First of all, thank you!
I really like your great work with this library.

I'm doing some tests with Cloud Storage and I find it really inconvenient to have to change the filesystem at the library level and not in the user sketch.
I faced the same problem in some of my libraries and solved it passing the filesystem as parameter in the class contructor and by directly using a pointer to the parent class Stream when file access is needed (like upload for example).
This way you don't have to change the definitions in the library source every time.

Maybe this approach can be applied also to your work?

**Comment by mobizt** [comment]
Thanks for the recommendation.

Changing file system between external SD card and flash memory at runtime is possible as the library already provided, while changing between flash e.g. LittleFS and SPIFFS is not.

Fire system selection should be done at compile time and need to design which file system to work and related to some hardware or circuit design (SD or SD/MMC).
