### ISSUE TITLE
Error: Main stack(20007988) was overflow

### ISSUE THREAD

**Issue by mrjcbs** [mobizt/Firebase-ESP-Client#660]
The Example "Create Document" is not working with my Arduino WiFi R4.

The code is attached.

**Error Message:**
13:43:45.150 -> Fault on interrupt or bare metal(no OS) environment
13:43:45.150 -> Error: Main stack(20007988) was overflow
13:43:45.150 -> ===== Thread stack information =====
13:43:45.150 ->   addr: 20007b00    data: 00000000

Do you have any idea how i can solve this problem?

[Example.txt](https://github.com/mobizt/Firebase-ESP-Client/files/14650874/Example.txt)

**Comment by mobizt** [comment]
That device memory is not enough for use with this library that relies on BearSSL which may not work in some ARM and SAMD devices.

This is the know issue that cannot be fixed.

You can try [this better new library](https://github.com/mobizt/FirebaseClient).
