### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by BonbonHatzil** [mobizt/Firebase-ESP-Client#673]
Hello, I'm currently using an esp32-wroom-32 and a gc9a01 screen. My code is trying to get data from firebase real time database and display it on the screen. For the very first 3 min it works well, but unfortunately every 3 min (approximately) there is a freeze in my serial monitor and then a connection refused error. After a few seconds it goes back to work fine, and than after another 3 min it returns the same error. This makes it hard for my device to be always updated. I'm also using the latest version for all my libraries. I would love for help or advices, Thanks a lot!

This is my code:
#include <WiFiManager.h>          // https://github.com/tzapu/WiFiManager
#include <TFT_eSPI.h>             // https://github.com/Bodmer/TFT_eSPI
#include <Firebase_ESP_Client.h>  // Firebase ESP32 library

// Provide the token generation process info.
#include <addons/TokenHelper.h>

// Define the Firebase Data object
FirebaseData fbdo;

// Define the Firebase Auth and Config objects
FirebaseAuth auth;
FirebaseConfig config;

#define FIREBASE_HOST "******.firebasedatabase.app"  // Replace with your Firebase Realtime Database URL
#define FIREBASE_API_KEY "my_api_key"                          // Replace with your Firebase API Key
#define FIREBASE_PROJECT_ID "my_project_id"                                                    // Replace with your Firebase Project ID

TFT_eSPI tft = TFT_eSPI();  // Initialize TFT screen

const int SCREEN_WIDTH = 240;   // Update with your screen's diameter
const int SCREEN_HEIGHT = 240;  // Update with your screen's diameter
const int TEXT_MARGIN = 80;     // Margin from the screen's edge

String CURRENT_DATA = "";  // Environment variable to store the current data

// Function to draw wrapped text
void drawWrappedText(const String &text, int x, int y, int width, int lineHeight) {
  int cursorX = x + TEXT_MARGIN;  // Adjusted for margins
  int cursorY = y - 10;

  String currentLine = "";
  String word = "";

  for (int i = 0; i < text.length(); i++) {
    char c = text.charAt(i);

    // Check if current character is a space or newline
    if (c == ' ' || c == '\n') {
      // Draw the current line if it fits, otherwise move to the next line
      int lineWidth = tft.textWidth(currentLine);

      if (cursorX + lineWidth > width - 20) {  // Adjusted for margins
        tft.drawString(currentLine, cursorX, cursorY);
        cursorY += lineHeight;
        currentLine = "";
      } else {
        currentLine += ' ';
      }
    } else {
      // Add character to current word or line
      currentLine += c;
    }
  }

  // Draw the last line
  if (currentLine.length() > 0) {
    tft.drawString(currentLine, cursorX, cursorY);
  }
}

void drawCenteredText(const String &text, int width, int height) {
  tft.setTextDatum(MC_DATUM);  // Middle Center Datum
  tft.drawString(text, width / 2, height / 2);
}

String getFirebaseValue() {
  if (Firebase.RTDB.getString(&fbdo, "/my_key")) {
    if (fbdo.dataType() == "string") {
      String newData = fbdo.stringData();
      return newData;
    }
  } else {
    Serial.println("Failed to get data from Firebase");
    Serial.println("REASON: " + fbdo.errorReason());
    return "";
  }
  return "";
}

void initializeFirebase() {
  // Initialize Firebase
  config.host = FIREBASE_HOST;
  config.api_key = FIREBASE_API_KEY;
  auth.user.email = "my_email";   // Replace with your Firebase Auth email
  auth.user.password = "my_password";  // Replace with your Firebase Auth password

  // Assign the callback function for the long running token generation task
  config.token_status_callback = tokenStatusCallback;  // see addons/TokenHelper.h

  Firebase.reconnectWiFi(true);
  
  Firebase.begin(&config, &auth);
}

void setup() {
  Serial.begin(115200);

  // Initialize the TFT screen
  tft.init();
  tft.setRotation(1);  // Adjust based on your screen orientation
  tft.fillScreen(TFT_BLACK);
  tft.setTextColor(TFT_WHITE);
  tft.setTextSize(1);
  tft.setTextDatum(MC_DATUM);  // Middle Center Datum
  tft.drawString("Starting...", SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2);

  // // Initialize WiFiManager
  WiFiManager wifiManager;

  // Uncomment to reset saved WiFi credentials (for testing)
  // wifiManager.resetSettings();

  // Automatically connect to saved WiFi or start an access point for configuration
  if (!wifiManager.autoConnect("ESP32_AP")) {
    Serial.println("Failed to connect to WiFi. Restarting...");
    tft.fillScreen(TFT_BLACK);
    tft.drawString("WiFi connection failed", SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2);
    ESP.restart();
  }

  // If you get here, you have connected to the WiFi
  Serial.println("Connected to WiFi!");
  tft.fillScreen(TFT_BLACK);
  tft.drawString("Connected to WiFi!", SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2);
  tft.drawString(WiFi.localIP().toString(), SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2 + 30);

  initializeFirebase();
  // // Optional: Set database read timeout
  // fbdo.setResponseSize(4096);
}

void loop() {
  // Continuously check the WiFi connection status
  if (WiFi.status() != WL_CONNECTED) {
    tft.fillScreen(TFT_BLACK);
    tft.drawString("WiFi not connected!", SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2);
    Serial.println("WiFi not connected!");
  } else {
    // Call the function to get the value from Firebase
    String newData = getFirebaseValue();
    if (newData != "" && newData != CURRENT_DATA) {
      CURRENT_DATA = newData;
      Serial.println("New data: " + newData);
      tft.fillScreen(TFT_BLACK);
      int lineHeight = 30;  // Adjusted line height for better spacing
      if (newData.length() <= 12) {
        tft.setTextSize(2);  // Increase text size for short messages
        drawCenteredText(newData, SCREEN_WIDTH, SCREEN_HEIGHT);
      } else {
        tft.setTextSize(1);  // Default text size for long messages
        drawWrappedText(newData, 40, TEXT_MARGIN, SCREEN_WIDTH, lineHeight);
      }
    }
  }
  // Check the connection status every 0.5 seconds
  delay(500);
}

This is my settings:
![image](https://github.com/mobizt/Firebase-ESP-Client/assets/174965381/227ec72b-827e-46ed-976f-2833957cc8ff)

This is my serial monitor:
![image](https://github.com/mobizt/Firebase-ESP-Client/assets/174965381/116bef11-d64b-4aa0-a5e1-025caf6dee2a)

**Comment by mobizt** [comment]
You have to follow the library examples and read every comment in the examples.

By calling get in the loop every 500 ms is a bad idea.
