### ISSUE TITLE
firebase esp32 client library clashes with esp mail client library

### ISSUE THREAD

**Issue by alabadan01** [mobizt/Firebase-ESP-Client#674]
i am doing a fingerprint attendance system using real-time firebase as the databse and also sending the attendance sheet after every lecture to an email acccount for later purposes and reasons. However, there is a compilation issue at the end of the journey. further investigations shows that there is a conflict between the both libraries being used. something indicating that 
![Screenshot_2024-08-10_00-06-23](https://github.com/user-attachments/assets/fdcd02b3-1c1d-4333-b9ca-11a5d643b909)
Both libraries are defining the same BSSL_TCP_Client class and its methods, causing multiple definition errors.
The error messages indicate that functions from BSSL_TCP_Client are defined in both libraries, leading to conflicts during linking.

**IDE and its version:**
 - Arduino,
 - Version [2.3.2]

**Comment by mobizt** [comment]
This library is end of life.

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP-Client?tab=readme-ov-file#we-have-moved-to-the-new-library

**Comment by mobizt** [comment]
Both libraries have the folder `src/client/SSLClient`, which you have to remove one which depending on which library was already included it.

if `ESP_Mail_Client.h` was included after `FirebaseXXXXX.h`, the folder [src/client/SSLClient](https://github.com/mobizt/ESP-Mail-Client/tree/master/src/client/SSLClient) in the `ESP-Mail-Client` library installation folder should be removed.

**Comment by alabadan01** [comment]
using the new library and its the same. the evidence of this installation is in the screenshot showing its been installed
![Uploading Screenshot_2024-08-02_09-42-42.png…]()
![Uploading Screenshot_2024-08-02_09-42-42.png…]()

![Uploading Screenshot_2024-08-10_00-06-23.png…]()

**Comment by mobizt** [comment]
Read my post above again.

**Comment by mobizt** [comment]
You have to uninstall all Firebase libraries and install only one and follow my comment above for redundant folders deletion.

**Comment by alabadan01** [comment]
ive got new errors

**Comment by mobizt** [comment]
Nothing is error if you follow my comment correctly.

**Comment by alabadan01** [comment]
do i use the firebase client library now?

**Comment by alabadan01** [comment]
the conflict is now with the firebse json library and the firebase esp32 library

**Comment by mobizt** [comment]
https://github.com/mobizt/Firebase-ESP32?tab=readme-ov-file#we-have-moved-to-the-new-library

**Comment by mobizt** [comment]
If you want to use new library, you have to read the documentation thoroughly and follow the library examples.
