### ISSUE TITLE
eventType always returns put, also when database entry is deleted

### ISSUE THREAD

**Issue by casvanluijtelaar** [mobizt/Firebase-ESP-Client#68]
i'm trying to recognize in a rtd stream when an item gets added or deleted, but I can't tell which is which because eventtype is always "put"

![image](https://user-images.githubusercontent.com/67225314/118626031-cf0dd880-b7ca-11eb-843c-1358868f4d6f.png)

**Comment by casvanluijtelaar** [comment]
using the stream callback example

**Comment by mobizt** [comment]
The event type was taken from Firebase server event payload. 

You should read this [Firebase RTDB API document](https://firebase.google.com/docs/reference/rest/database#section-streaming).

**Comment by mobizt** [comment]
Only **put** and **patch** event types related to data changes event.

**Comment by casvanluijtelaar** [comment]
so there is no way of knowing when a specific item is removed?

**Comment by mobizt** [comment]
You should try and investigate, how it is going.

When you remove the node, the parsed response payload info are

```
stream path: /your/stream/node
event path: /path/to/deleted/node <----- where the deleted node relative to stream node path
event type: put <---  for set, push and delete functions while patch is for update node (updateNode) function.
data type: null <------ this states the data changes with delete
```

**Comment by casvanluijtelaar** [comment]
that's what i'm looking for! dataPath stays the same but dataType is null. thanks!
