### ISSUE TITLE
Compile error - Missing files

### ISSUE THREAD

**Issue by WouterJansen** [mobizt/Firebase-ESP-Client#9]
I get the following error compiling with Arduino IDE for my AI Thinker ESP32-CAM:

`Firebase_ESP_Client.h:38:26: fatal error: rtdb/FB_RTDB.h: No such file or directory`

I'm guessing maybe the _rtdb_ folder was never committed and added to the repository with the refactor between 1.0.3 and 1.1.1. The issue does not exist on 1.0.3

**Comment by mobizt** [comment]
You said right.

Thank you for address this issue due to folder renaming and the Github publish script is not modified the include files.

I will republish again and update.

**Comment by mobizt** [comment]
I update the library already, please update.

**Comment by mobizt** [comment]
Now the library updated to version 1.1.3. You can update now.
