### ISSUE TITLE
getInt function takes a lot of time

### ISSUE THREAD

**Issue by EmreDUR** [mobizt/Firebase-ESP-Client#99]
Hello mobizt. I'm using your library and it made my project a lot better. However I'm having a little bit of trouble with getInt function.

I'm trying to read a simple integer value (varies from 0 to 100 by the way) on the Realtime Database and it sometimes takes less than a second to procces and sometimes it takes more than 10 seconds to read a single value. I don't really have a lot of experience with Firebase so I'm sorry if I'm doing something wrong. 

Is there a way that I can make the procces faster or set the timeout correctly. I tried setReadTimeout function but it does not affect anything at all.

My code is too long so I'm just sharing the Firebase related parts so please let me know if something is missing.

```
#include <Firebase_ESP_Client.h>

int fanspeed;

#define DATABASE_URL ""
#define DATABASE_SECRET ""

FirebaseData firebaseData;
FirebaseAuth auth;
FirebaseConfig config;

void setup() {
  config.database_url = DATABASE_URL;
  config.signer.tokens.legacy_token = DATABASE_SECRET;

  Firebase.begin(&config, &auth);
  Firebase.reconnectWiFi(true);
  Firebase.RTDB.setReadTimeout(&firebaseData, 100);
}

void loop(){
    if(Firebase.ready())
    {
      Firebase.RTDB.getInt(&firebaseData, "/cYTdHBtkME/fanspeed2",&fanspeed);
    }

    Serial.print("Fan Speed: ");
    Serial.println(fanspeed);
}
```

**Comment by mobizt** [comment]
Set read time out is the server side option not a client.
https://firebase.google.com/docs/reference/rest/database#section-param-timeout

Your example code is not efficient and **incorrect use of** the library and all other REST API based libraries, to send the request to read the data from server continuously all the time. 

Do like that is the same as you press F5 key at web browser to refresh the web page repeatedly. 

The time for data transfer is vary and not related to the library, it depends on many factors e.g. reserved buffer in ESP8266 and network condition, which [described here](https://github.com/mobizt/Firebase-ESP-Client#speed-of-data-transfer).

To listen or monitor the value changes on server, use [stream](https://github.com/mobizt/Firebase-ESP-Client/tree/main/examples/RTDB/DataChangesListener) instead.

You should use [Discussions](https://github.com/mobizt/Firebase-ESP-Client/discussions) for question or help.
